dist: trusty
sudo: false
language: cpp

addons:
    apt:
        sources:
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
        packages:
            - clang-3.7
            - g++-5
            - gcc-5
            - cmake
            - cmake-data

compiler:
    - gcc
    - clang

before_script:
    - mkdir build
    - cd build
    - cmake ..
    - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
    - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi

script:
    - make
    - ctest
