image: Visual Studio 2015

build_script:
  - git clone https://github.com/4iar/build-libcurl-windows.git
  - cd build-libcurl-windows
  - build.bat
  - cd ..
  - mkdir build
  - cd build
  - cmake .. -G"Visual Studio 14 2015 Win64"
  - cmake --build .

test_script:
  - ctest -V -C Debug
