nicehash-api-cpp: Client Class Reference
Client Class Reference
#include <client.hpp>
Public Member Functions
virtual ~ Client ()
virtual std::string get (std::string const url)
GET request the provided url and return the response body as a string.
Detailed Description
Definition at line 6 of file client.hpp.
Constructor & Destructor Documentation
~ Client()
virtual Client::~ Client () inline virtual
Definition at line 9 of file client.hpp.
Member Function Documentation
get()
std::string Client::get (std::string const url) virtual
GET request the provided url and return the response body as a string.
Parameters
url the URL to GET request
Returns
The response body
Definition at line 14 of file get.cpp.
References WriteCallback().
Referenced by NiceHashApi::getApiVersion(), NiceHashApi::getAverageGlobalStats(), NiceHashApi::getCurrentGlobalStats(), NiceHashApi::getDetailedProviderStats(), NiceHashApi::getOrdersByAlgorithm(), NiceHashApi::getProviderStats(), and NiceHashApi::getProviderWorkerStats().
The documentation for this class was generated from the following files:
client.hpp
get.cpp